### ISSUE TITLE
vcd-number-with-unit-form-input setValidators not working

### ISSUE THREAD

**Issue by ttsvetanov-vmware** [vmware/vmware-cloud-director-ui-components#133]
I tried to add validators with setValidators(), but it doesn't work.
https://stackblitz.com/edit/angular-ivy-crhd9f

**Comment by ttsvetko** [comment]
Hi folks, any progress on this one? We are using this component in our new wizards and not showing error messages for that control makes our functionality broken - users are not aware why `next` button is disabled because of invalid value or required input. Can you please let us know if you plan to fix it for Zeus?

**Comment by irahov** [comment]
I start working on this

**Comment by irahov** [comment]
Fixed in 1.0.0-dev.37
