### ISSUE TITLE
@vcd/ui-doc-lib@next' is not in the npm registry

### ISSUE THREAD

**Issue by somnathswami** [vmware/vmware-cloud-director-ui-components#40]
got an issue while ng-serve and tried with `npm install @vcd/ui-doc-lib@next ` command but it gives me error saying @vcd/ui-doc-lib@next' is not in the npm registry

**Comment by juanmendes** [comment]
Hi Som, we're sorry this is yet published. We are hoping to release this soon. We are working on moving this UI Doc Library to a different repo, since this repo is more specific to a VMware Cloud Director.  We are still finishing up the library before the initial release. If you'd really like to give it a try, I can publish a release that you can play with and try it out. Ping us back here

**Comment by juanmendes** [comment]
@somnathswami The doc library is now available at https://github.com/vmware/live-docs/blob/master/projects/ng-live-docs/README.md
